#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
import sys
import json

import stream_installer

status_dir = None
if len(sys.argv) == 1:
    status_dir = "/fsp_sss_stream/smd/stop"
else:
    sys.exit(2)

def stop_and_remove(files):
    for filename in files:
        path = "{dir}/{name}".format(dir=status_dir, name=filename)
        status = None
        with open(path) as fileobj:
            status = json.load(fileobj)
        if status:
            service_name = status["service_name"]
            stream_installer.stop_service(service_name, dir=status_dir)
        os.remove(path)

files = []
try:
    files = os.listdir(status_dir)
except OSError as e:
    print e
else:
    stop_and_remove(files)
