#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import subprocess

if len(sys.argv) != 2:
    sys.exit(2)

service_names = sys.argv[1]
print "service_names: {0}".format(service_names)

builtin_services = ["ss", "sc.py", "gs", "gc.py", "cp", "sp", "rule.py", "ma", "ms", "stream_as", "group_as", "access", "ice"]

list_service_name = service_names.split()

while(len(list_service_name) > 0) :
    service_name = list_service_name.pop()

    if service_name in builtin_services:
        subprocess.call(["./stop_one", service_name])
    elif service_name in ["all", "all_services", "__all__"]:
        subprocess.call(["./stop_all"])
    else:
        script = "./stop_{0}".format(service_name)
        subprocess.call([script])
